# Generated by Django 5.2.5 on 2025-08-19 16:32

from django.db import migrations

def create_user_classes(apps, schema_editor):
    UserClass = apps.get_model('assets', 'UserClass')
    Rights = apps.get_model('assets', 'Rights')

    admin_class = UserClass.objects.create(name='Admin')
    it_staff_class = UserClass.objects.create(name='IT Staff')
    basic_user_class = UserClass.objects.create(name='Basic User')

    Rights.objects.create(
        user_class=admin_class,
        can_view_admin=True,
        can_view_assets=True,
        can_view_asset_overview=True,
        can_view_user_management=True,
        can_view_reports=True
    )
    Rights.objects.create(
        user_class=it_staff_class,
        can_view_admin=False,
        can_view_assets=True,
        can_view_asset_overview=True,
        can_view_user_management=False,
        can_view_reports=True
    )
    Rights.objects.create(
        user_class=basic_user_class,
        can_view_admin=False,
        can_view_assets=False,
        can_view_asset_overview=True,
        can_view_user_management=False,
        can_view_reports=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_customuser_access_level'),
    ]

    operations = [
        migrations.RunPython(create_user_classes),
    ]
