# Generated by Django 5.2.5 on 2025-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_auto_20250819_1632"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="warranty_expiration",
            field=models.DateField(blank=True, null=True),
        ),
    ]
